

FROM node:12.2.0-alpine as build
WORKDIR /timetables
ENV PATH /timetables/node_modules/.bin:$PATH
COPY package.json /timetables/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY . /timetables
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /timetables/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
